Global:
  algorithm: CRNN
  use_gpu: false   #cpu 为false
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_CRNN
  save_epoch_step: 300
  eval_batch_step: 500
  train_batch_size_per_card: 100       #训练时，每次“塞入”的图片数量，计算机性能不足，可以适当调小
  test_batch_size_per_card: 256
  image_shape: [3, 32, 100]            # 图片形状[c, h, w]
  max_text_length: 1000
  character_type: en                   #en ，表示识别字典集为0-9，a-z;如自定义 修改为“ch”
  character_dict_path:                 #自定义字典集路径
  loss_type: ctc
  distort: true
  debug: false
  reader_yml: ../configs/rec/rec_icdar15_reader.yml
  pretrain_weights: ../pretrain_models/rec_mv3_none_bilstm_ctc/best_accuracy  #预训练模型地址
  #训练时用
#  checkpoints:
#  save_inference_dir:
#  infer_img:
  #评估时 指定“checkpoints”为N代训练后的模型
#  checkpoints: ./output/rec_CRNN/iter_epoch_900
#  save_inference_dir:
#  infer_img:
  #测试 指定“infer_img”为测试集路径
#  checkpoints: ./output/rec_CRNN/iter_epoch_900
#  save_inference_dir:
#  infer_img: ../train_data/ic15_data/test/
  # 将“检测”训练模型转化为推理模型
  # 将“checkpoints”指定为自己训练处的模型文件所在路径
  # 将“save_inference_dir”表示导出的推理模型路径
  checkpoints: ./output/rec_CRNN/iter_epoch_900
  save_inference_dir: ../inference/suntech_v1.1_rec_infer
  infer_img:

Architecture:
  function: ppocr.modeling.architectures.rec_model,RecModel

Backbone:
  function: ppocr.modeling.backbones.rec_mobilenet_v3,MobileNetV3
  scale: 0.5
  model_name: large

Head:
  function: ppocr.modeling.heads.rec_ctc_head,CTCPredict
  encoder_type: rnn
  SeqRNN:
    hidden_size: 96
    
Loss:
  function: ppocr.modeling.losses.rec_ctc_loss,CTCLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.0005
  beta1: 0.9
  beta2: 0.999
  decay:
    function: cosine_decay
    step_each_epoch: 20
    total_epoch: 1000
